# Generated by Django 3.2.5 on 2022-06-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('dept', models.CharField(choices=[('civil', 'Civil Engineering'), ('mech', 'Mechanical Engineering'), ('ece', 'Electronics and Communication'), ('cse', 'Computer Science and Engineering'), ('min', 'Mining Engineering'), ('meta', 'Metalurgical Engineering'), ('chem', 'Chemical Engineering'), ('elec', 'Electrical Engineering')], default='civil', max_length=10)),
                ('degree', models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('phd', 'PhD')], default='btech', max_length=10)),
                ('year_study', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
