# Generated by Django 3.2.5 on 2022-06-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointLoadModel',
        ),
        migrations.DeleteModel(
            name='PointMomentModel',
        ),
        migrations.DeleteModel(
            name='SupportModel',
        ),
        migrations.DeleteModel(
            name='UDLModel',
        ),
    ]
