# Generated by Django 3.2.5 on 2022-06-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0002_auto_20220607_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='beammodel',
            name='beam_left_support',
            field=models.CharField(choices=[('pin', 'Pin/Hinge'), ('roller', 'Roller'), ('fix', 'Fixed')], default='pin', max_length=10),
        ),
    ]
