# Generated by Django 3.2.5 on 2022-06-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0003_beammodel_beam_left_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='beammodel',
            name='beam_right_support',
            field=models.CharField(choices=[('pin', 'Pin/Hinge'), ('roller', 'Roller'), ('fix', 'Fixed')], default='roller', max_length=10),
        ),
    ]
